<a href="https://colab.research.google.com/github/Severus25/Ola-data-engineering-project/blob/main/Transformation_Logic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("ola_data.csv") # Importing the DataSet

In [3]:
df.head() #Viewing the Dataset sample

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01 00:00:00,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01 00:00:00,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01 00:00:00,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01 00:00:00,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01 00:00:00,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [4]:
df.info() #This will show the type of the datatype i n the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  object
 2   tpep_dropoff_datetime  100000 non-null  object
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: float64(12), int64(4), object(3)
memory usage: 14.5+ MB

In [5]:
df['tpep_pickup_datetime']=pd.to_datetime(df['tpep_pickup_datetime']) #To Convert to Datetime
df['tpep_dropoff_datetime']=pd.to_datetime(df['tpep_dropoff_datetime']) #To Convert to Datetime

In [6]:
df.info() #This will show the type of the datatype i n the columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   VendorID               100000 non-null  int64
 1   tpep_pickup_datetime   100000 non-null  datetime64[ns]
 2   tpep_dropoff_datetime  100000 non-null  datetime64[ns]
 3   passenger_count        100000 non-null  int64
 4   trip_distance          100000 non-null  float64
 5   pickup_longitude       100000 non-null  float64
 6   pickup_latitude        100000 non-null  float64
 7   RatecodeID             100000 non-null  int64
 8   store_and_fwd_flag     100000 non-null  object
 9   dropoff_longitude      100000 non-null  float64
 10  dropoff_latitude       100000 non-null  float64
 11  payment_type           100000 non-null  int64
 12  fare_amount            100000 non-null  float64
 13  extra                  100000 non-null  float64
 14  mta_tax                100000 non-null  float64
 15  tip_amount             100000 non-null  float64
 16  tolls_amount           100000 non-null  float64
 17  improvement_surcharge  100000 non-null  float64
 18  total_amount           100000 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 14.5+ MB

In [7]:
datetime_dim=df[['tpep_pickup_datetime','tpep_dropoff_datetime']].drop_duplicates().reset_index(drop=True)

In [8]:
type(datetime_dim)

pandas.core.frame.DataFrame

In [9]:
datetime_dim['pick_hour']=datetime_dim['tpep_pickup_datetime'].dt.hour
datetime_dim['pick_day']=datetime_dim['tpep_pickup_datetime'].dt.day
datetime_dim['pick_month']=datetime_dim['tpep_pickup_datetime'].dt.month
datetime_dim['pick_year']=datetime_dim['tpep_pickup_datetime'].dt.year
datetime_dim['pick_weekday']=datetime_dim['tpep_pickup_datetime'].dt.weekday

In [10]:
datetime_dim

,tpep_pickup_datetime,tpep_dropoff_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday
0,2016-03-01 00:00:00,2016-03-01 00:07:55,0,1,3,2016,1
1,2016-03-01 00:00:00,2016-03-01 00:11:06,0,1,3,2016,1
2,2016-03-01 00:00:00,2016-03-01 00:31:06,0,1,3,2016,1
3,2016-03-01 00:00:00,2016-03-01 00:00:00,0,1,3,2016,1
4,2016-03-01 00:00:01,2016-03-01 00:16:04,0,1,3,2016,1
...,...,...,...,...,...,...,...
99848,2016-03-01 06:17:10,2016-03-01 06:22:15,6,1,3,2016,1
99849,2016-03-01 06:17:10,2016-03-01 06:32:41,6,1,3,2016,1
99850,2016-03-01 06:17:10,2016-03-01 06:37:23,6,1,3,2016,1
99851,2016-03-01 06:17:10,2016-03-01 06:22:09,6,1,3,2016,1
99852,2016-03-01 06:17:11,2016-03-01 06:22:00,6,1,3,2016,1

In [11]:
datetime_dim['drop_hour']=datetime_dim['tpep_dropoff_datetime'].dt.hour
datetime_dim['drop_day']=datetime_dim['tpep_dropoff_datetime'].dt.day
datetime_dim['drop_month']=datetime_dim['tpep_dropoff_datetime'].dt.month
datetime_dim['drop_year']=datetime_dim['tpep_dropoff_datetime'].dt.year
datetime_dim['drop_weekday']=datetime_dim['tpep_dropoff_datetime'].dt.weekday

In [12]:
datetime_dim['datetime_id']=datetime_dim.index

In [13]:
datetime_dim[['datetime_id','tpep_pickup_datetime','pick_hour','pick_day',
              'pick_month','pick_year',
             'pick_weekday','tpep_dropoff_datetime','drop_hour','drop_day',
              'drop_month',
             'drop_year','drop_weekday']]

,datetime_id,tpep_pickup_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday,tpep_dropoff_datetime,drop_hour,drop_day,drop_month,drop_year,drop_weekday
0,0,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01 00:00:01,0,1,3,2016,1,2016-03-01 00:16:04,0,1,3,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99848,99848,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:15,6,1,3,2016,1
99849,99849,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:32:41,6,1,3,2016,1
99850,99850,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:37:23,6,1,3,2016,1
99851,99851,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:09,6,1,3,2016,1
99852,99852,2016-03-01 06:17:11,6,1,3,2016,1,2016-03-01 06:22:00,6,1,3,2016,1

In [14]:
datetime_dim=datetime_dim[['datetime_id','tpep_pickup_datetime','pick_hour','pick_day',
              'pick_month','pick_year',
             'pick_weekday','tpep_dropoff_datetime','drop_hour','drop_day',
              'drop_month',
             'drop_year','drop_weekday']]
datetime_dim

,datetime_id,tpep_pickup_datetime,pick_hour,pick_day,pick_month,pick_year,pick_weekday,tpep_dropoff_datetime,drop_hour,drop_day,drop_month,drop_year,drop_weekday
0,0,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:07:55,0,1,3,2016,1
1,1,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:11:06,0,1,3,2016,1
2,2,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:31:06,0,1,3,2016,1
3,3,2016-03-01 00:00:00,0,1,3,2016,1,2016-03-01 00:00:00,0,1,3,2016,1
4,4,2016-03-01 00:00:01,0,1,3,2016,1,2016-03-01 00:16:04,0,1,3,2016,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99848,99848,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:15,6,1,3,2016,1
99849,99849,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:32:41,6,1,3,2016,1
99850,99850,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:37:23,6,1,3,2016,1
99851,99851,2016-03-01 06:17:10,6,1,3,2016,1,2016-03-01 06:22:09,6,1,3,2016,1
99852,99852,2016-03-01 06:17:11,6,1,3,2016,1,2016-03-01 06:22:00,6,1,3,2016,1

In [15]:
passenger_count_dim=df[['passenger_count']].drop_duplicates().reset_index(drop=True)
passenger_count_dim['passenger_count_id']=passenger_count_dim.index
passenger_count_dim=passenger_count_dim[['passenger_count_id','passenger_count']]

trip_distance_dim=df[['trip_distance']].drop_duplicates().reset_index(drop=True)
trip_distance_dim['trip_distance_id']=trip_distance_dim.index
trip_distance_dim=trip_distance_dim[['trip_distance_id','trip_distance']]

In [16]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,2016-03-01,2016-03-01 00:07:55,1,2.50,-73.976746,40.765152,1,N,-74.004265,40.746128,1,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,2016-03-01,2016-03-01 00:11:06,1,2.90,-73.983482,40.767925,1,N,-74.005943,40.733166,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2016-03-01,2016-03-01 00:31:06,2,19.98,-73.782021,40.644810,1,N,-73.974541,40.675770,1,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,2016-03-01,2016-03-01 00:00:00,3,10.78,-73.863419,40.769814,1,N,-73.969650,40.757767,1,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,2016-03-01,2016-03-01 00:00:00,5,30.43,-73.971741,40.792183,3,N,-74.177170,40.695053,1,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [17]:
trip_distance_dim.head()

   trip_distance_id  trip_distance
0                 0           2.50
1                 1           2.90
2                 2          19.98
3                 3          10.78
4                 4          30.43

In [18]:
rate_code_type={
    1:"Standard Rate",
    2:'JKF',
    3:'Newark',
    4:'Nassau or Westchester',
    5:'Negotiated fare',
    6:'Group Ride'
}

rate_code_dim=df[['RatecodeID']].drop_duplicates().reset_index(drop=True)
rate_code_dim['rate_code_id']=rate_code_dim.index
rate_code_dim['rate_code_name']=rate_code_dim['RatecodeID'].map(rate_code_type)
rate_code_dim=rate_code_dim[['rate_code_id','RatecodeID','rate_code_name']]

In [19]:
rate_code_dim['rate_code_name'].head()

0            Standard Rate
1                   Newark
2                      JKF
3          Negotiated fare
4    Nassau or Westchester
Name: rate_code_name, dtype: object

In [20]:
pickup_location_dim=df[['pickup_latitude','pickup_longitude']].drop_duplicates().reset_index(drop=True)
pickup_location_dim['pickup_location_id']=pickup_location_dim.index
pickup_location_dim=pickup_location_dim[['pickup_location_id','pickup_latitude','pickup_longitude']]

drop_location_dim=df[['dropoff_longitude','dropoff_latitude']].drop_duplicates().reset_index(drop=True)
drop_location_dim['dropoff_location_id']=drop_location_dim.index
drop_location_dim=drop_location_dim[['dropoff_location_id','dropoff_longitude','dropoff_latitude']]

In [21]:
pickup_location_dim.head()

   pickup_location_id  pickup_latitude  pickup_longitude
0                   0        40.765152        -73.976746
1                   1        40.767925        -73.983482
2                   2        40.644810        -73.782021
3                   3        40.769814        -73.863419
4                   4        40.792183        -73.971741

In [22]:
payment_type_name={
    1:"Credit card",
2:"Cash",
3:"No charge",
4:"Dispute",
5:"Unknown",
6:"Voided trip"


}

payment_type_dim=df[['payment_type']].drop_duplicates().reset_index(drop=True)
payment_type_dim['payment_type_id']=payment_type_dim.index
payment_type_dim['payment_type_name']=payment_type_dim['payment_type'].map(payment_type_name)
payment_type_dim=payment_type_dim[['payment_type_id','payment_type','payment_type_name']]

In [23]:
payment_type_dim.head()

   payment_type_id  payment_type payment_type_name
0                0             1       Credit card
1                1             2              Cash
2                2             3         No charge
3                3             4           Dispute

In [24]:
#let's Create the fact table and Connect all the dimension tables

fact_table=df.merge(datetime_dim,on=['tpep_pickup_datetime','tpep_dropoff_datetime'])\
            .merge(passenger_count_dim,on='passenger_count')\
            .merge(trip_distance_dim,on=['trip_distance'])\
            .merge(pickup_location_dim,on=['pickup_latitude','pickup_longitude'])\
            .merge(drop_location_dim,on=['dropoff_latitude','dropoff_longitude'])\
            .merge(rate_code_dim,on='RatecodeID')\
            .merge(payment_type_dim,on='payment_type')\
            [['VendorID','datetime_id','passenger_count_id','trip_distance_id','rate_code_id',
             'store_and_fwd_flag','pickup_location_id','dropoff_location_id','payment_type_id'
             ,'fare_amount','extra','mta_tax','tip_amount','tolls_amount','improvement_surcharge',
             'total_amount']]

In [25]:
trip_distance_dim.head()

   trip_distance_id  trip_distance
0                 0           2.50
1                 1           2.90
2                 2          19.98
3                 3          10.78
4                 4          30.43

In [26]:
rate_code_dim['rate_code_name'].head()

0            Standard Rate
1                   Newark
2                      JKF
3          Negotiated fare
4    Nassau or Westchester
Name: rate_code_name, dtype: object

In [27]:
fact_table.head()

,VendorID,datetime_id,passenger_count_id,trip_distance_id,rate_code_id,store_and_fwd_flag,pickup_location_id,dropoff_location_id,payment_type_id,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,1,0,0,0,0,N,0,0,0,9.0,0.5,0.5,2.05,0.00,0.3,12.35
1,1,1,0,1,0,N,1,1,0,11.0,0.5,0.5,3.05,0.00,0.3,15.35
2,2,2,1,2,0,N,2,2,0,54.5,0.5,0.5,8.00,0.00,0.3,63.80
3,2,3,2,3,0,N,3,3,0,31.5,0.0,0.5,3.78,5.54,0.3,41.62
4,2,3,3,4,1,N,4,4,0,98.0,0.0,0.0,0.00,15.50,0.3,113.80

In [33]:
def get_data():
  return {
        "datetime_dim":datetime_dim.to_dict(orient='dict'),
        "passenger_count_dim":passenger_count_dim.to_dict(orient='dict'),
        "trip_distance_dim":trip_distance_dim.to_dict(orient='dict'),
        "rate_code_dim":rate_code_dim.to_dict(orient='dict'),
        "pickup_location_dim":pickup_location_dim.to_dict(orient='dict'),
        "drop_location_dim":drop_location_dim.to_dict(orient='dict'),
        "payment_type_dim":payment_type_dim.to_dict(orient='dict'),
        "fact_table":fact_table.to_dict(orient='dict')
    }
print(get_data)

<function get_data at 0x7d245291b740>